name: CI workflow validation

on:
  push:
    branches:
      - devilution/full-game-ui
    paths:
      - '.github/workflows/**'
      - '.github/ci-trigger'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
